
services:
  ebac-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "eliezer"
    ports:
      - "5433:5432"
    volumes:
      - /C:/codes/BackEnd-Java/docker/PostgreSQL:/var/lib/postgresql/data 
    networks:
      -    postgres-ebac-network
      
  ebac-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "eliezer@yahoo.com.br"
      PGADMIN_DEFAULT_PASSWORD: "994623470"
    ports:
      - "16543:80"
    depends_on:
      - ebac-postgres-compose
    networks:
      - postgres-ebac-network

  ebac-mysql-compose:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: 'vendas_online'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    ports:
      - "3306:3306"

networks: 
  postgres-ebac-network:
    driver: bridge